--[[--------------------------------------------------------------------------
    WoW Task Manager - UI/Pages/System.lua

    Client facts and the live capability matrix.

    The matrix is not documentation copied into the UI - it is generated by
    Core/Capabilities.lua from actual API probes at login, so what you see here
    is what this specific client really supports.  Rows that are unavailable
    stay visible with the reason, because a limitation you can read is more
    useful than a feature that quietly is not there.
----------------------------------------------------------------------------]]

local ADDON_NAME, WTM = ...

local C      = WTM.C
local UI     = WTM.UI
local Theme  = UI.Theme
local T      = Theme.Get
local M      = Theme.metrics
local Fmt    = WTM.Format
local Compat = WTM.Compat

local Page = UI.RegisterPage("system", {})

local capRows = {}

local STATE_LABEL = {
    yes     = { text = "Available",  tone = "ok"    },
    partial = { text = "Heuristic",  tone = "warn"  },
    profile = { text = "Needs profiling", tone = "warn" },
    no      = { text = "Unavailable", tone = "muted" },
}

function Page:Build(frame)
    local pad = M.padding

    ------------------------------------------------------------------
    -- Client info card
    ------------------------------------------------------------------
    self.infoCard = UI.Card(frame, "CLIENT", {})
    self.infoCard:SetWidth(380)
    self.infoCard:SetPoint("TOPLEFT", pad, -pad)
    self.infoCard:SetHeight(370)

    self.infoRows = {}
    local INFO_KEYS = {
        "Client", "Version", "Build", "Build date", "Interface", "Project ID",
        "Locale", "Realm", "Character",
        "Screen resolution", "UI scale", "Addon folder count", "Loaded addons",
        "Lua memory", "Addon version", "Library backend",
        "Database schema", "Saved database size", "Event monitoring",
        "Spike detection", "Baseline",
    }
    for i, label in ipairs(INFO_KEYS) do
        local row = UI.StatRow(self.infoCard.content, label)
        row:SetPoint("TOPLEFT", 0, -(i - 1) * 17)
        row:SetPoint("TOPRIGHT", 0, -(i - 1) * 17)
        self.infoRows[label] = row
    end

    ------------------------------------------------------------------
    -- CVar card
    ------------------------------------------------------------------
    self.cvarCard = UI.Card(frame, "GRAPHICS CVARS", {})
    self.cvarCard:SetWidth(380)
    self.cvarCard:SetPoint("TOPLEFT", self.infoCard, "BOTTOMLEFT", 0, -M.cardGap)
    self.cvarCard:SetPoint("BOTTOM", frame, "BOTTOM", 0, pad)

    self.cvarNote = UI.Text(self.cvarCard.content, "tiny", "textMuted")
    self.cvarNote:SetPoint("BOTTOMLEFT")
    self.cvarNote:SetPoint("BOTTOMRIGHT")
    self.cvarNote:SetJustifyH("LEFT")
    UI.Wrap(self.cvarNote)
    self.cvarNote:SetText("Only CVars that actually return a value on this client are listed. Nothing here is written to; protected and read-only CVars are never touched.")

    self.cvarRows = {}
    self.cvarList = {}

    ------------------------------------------------------------------
    -- Capability matrix
    ------------------------------------------------------------------
    self.capCard = UI.Card(frame, "CAPABILITY MATRIX", {})
    self.capCard:SetPoint("TOPLEFT", self.infoCard, "TOPRIGHT", M.cardGap, 0)
    self.capCard:SetPoint("BOTTOMRIGHT", -pad, pad)

    self.capList = UI.ScrollList(self.capCard.content, 20,
        function(parent)
            local row = CreateFrame("Frame", nil, parent)
            row.label = UI.Text(row, "small", "textPrimary")
            row.label:SetPoint("LEFT", 4, 0)
            row.label:SetWidth(210)
            row.label:SetJustifyH("LEFT")

            row.state = UI.Text(row, "small", "textSecondary")
            row.state:SetPoint("LEFT", row.label, "RIGHT", 8, 0)
            row.state:SetWidth(120)

            row.note = UI.Text(row, "tiny", "textMuted")
            row.note:SetPoint("LEFT", row.state, "RIGHT", 8, 0)
            row.note:SetPoint("RIGHT", row, "RIGHT", -6, 0)
            row.note:SetJustifyH("LEFT")

            -- The note is fitted to the cell, so the full text has to be
            -- reachable somewhere. Hovering the row is that somewhere.
            row:EnableMouse(true)
            row:SetScript("OnEnter", function(self2)
                if not self2.noteFull or self2.noteFull == "" then return end
                UI.ShowTooltip(self2, self2.label:GetText(), self2.noteFull)
            end)
            row:SetScript("OnLeave", UI.HideTooltip)
            return row
        end,
        function(row, entry)
            if entry.isHeader then
                row.label:SetText(entry.title)
                row.label:SetTextColor(T("accent"))
                row.state:SetText("")
                row.note:SetText("")
                row.noteFull = nil
            else
                row.label:SetText(entry.label)
                row.label:SetTextColor(T("textPrimary"))
                local info = STATE_LABEL[entry.state] or STATE_LABEL.no
                row.state:SetText(info.text)
                row.state:SetTextColor(Theme:Tone(info.tone))
                -- One line in a table cell. Fitted rather than clipped
                -- mid-word; the row's tooltip carries the whole note.
                row.note:SetText(UI.FitText(row.note, entry.note or ""))
                row.noteFull = entry.note or ""
            end
        end)
    self.capList:SetAllPoints(self.capCard.content)
end

function Page:OnShow() self:Refresh() end

--------------------------------------------------------------------------

local function ResolutionText()
    if Compat.api.GetPhysicalScreenSize then
        local w, h = Compat.SafeCall("GetPhysicalScreenSize", Compat.api.GetPhysicalScreenSize)
        if w and h then return ("%d x %d"):format(w, h) end
    end
    -- Fallback: UI units scaled back to pixels.
    local w = GetScreenWidth and GetScreenWidth() or 0
    local h = GetScreenHeight and GetScreenHeight() or 0
    local scale = UIParent:GetEffectiveScale()
    return ("~%d x %d (derived)"):format(w * scale, h * scale)
end

function Page:BuildCVarRows()
    local list = self.cvarList
    for i = #list, 1, -1 do list[i] = nil end

    local names = Compat.knownCVars or { "maxFPS", "maxFPSBk", "vsync", "gxVSync", "scriptProfile" }
    for _, name in ipairs(names) do
        local value = Compat.GetCVar(name)
        if value ~= nil then
            local writable, why = Compat.IsCVarWritable(name)
            list[#list + 1] = { name = name, value = value, writable = writable, why = why }
        end
    end

    for i, entry in ipairs(list) do
        local row = self.cvarRows[i]
        if not row then
            row = UI.StatRow(self.cvarCard.content, "")
            row:SetPoint("TOPLEFT", 0, -(i - 1) * 17)
            row:SetPoint("TOPRIGHT", 0, -(i - 1) * 17)
            self.cvarRows[i] = row
        end
        row:Show()
        row:SetLabel(entry.name .. (entry.writable and "" or "  (read-only)"))
        row:Set(tostring(entry.value), entry.writable and nil or "muted")
    end
    for i = #list + 1, #self.cvarRows do self.cvarRows[i]:Hide() end
end

function Page:Refresh()
    if not self.infoRows then return end

    local function set(key, value, tone)
        local row = self.infoRows[key]
        if row then row:Set(value, tone) end
    end

    local loaded = 0
    for _, record in WTM.Processes:Iterate() do
        if record.loaded then loaded = loaded + 1 end
    end

    set("Client",            Compat.flavorName)
    set("Version",           Compat.version)
    set("Build",             Compat.build)
    set("Build date",        Compat.buildDate)
    set("Interface",         tostring(Compat.tocVersion))
    set("Project ID",        Compat.projectID and tostring(Compat.projectID) or "not defined")
    set("Locale",            GetLocale())
    set("Realm",             GetRealmName())
    set("Character",         UnitName("player"))
    set("Screen resolution", ResolutionText())
    set("UI scale",          ("%.3f"):format(UIParent:GetEffectiveScale()))
    set("Addon folder count", tostring(#WTM.Processes.list))
    set("Loaded addons",     tostring(loaded))
    set("Lua memory",        Fmt.Memory(WTM.Memory.current.luaKB))
    set("Addon version",     C.VERSION)
    set("Library backend",   WTM.Ace.Describe())

    local schemaText, schemaTone = WTM.Database:DescribeSchema()
    set("Database schema", schemaText, schemaTone)
    set("Saved database size", Fmt.Bytes(WTM.Database:EstimateSizeBytes()))

    -- The mode name is the value; the paragraph explaining it belongs on the
    -- Settings page next to the control, not squeezed into a one-line cell.
    set("Event monitoring", WTM.Events:GetMode())

    local suppressionText, suppressionTone = WTM.Suppression:Status()
    set("Spike detection", suppressionText, suppressionTone)

    set("Baseline", WTM.FrameTime:IsBaselineReady()
        and ("%s settled over %d samples")
            :format(Fmt.Ms(WTM.FrameTime:GetBaseline()), WTM.FrameTime:GetBaselineSamples())
        or ("%s settling (%d samples) - absolute thresholds only until it does")
            :format(Fmt.Ms(WTM.FrameTime:GetBaseline()), WTM.FrameTime:GetBaselineSamples()),
        WTM.FrameTime:IsBaselineReady() and nil or "warn")

    self:BuildCVarRows()

    ------------------------------------------------------------------
    -- Capability rows (rebuilt only when the matrix changes)
    ------------------------------------------------------------------
    for i = #capRows, 1, -1 do capRows[i] = nil end
    for _, group in ipairs(WTM.Caps.GROUPS) do
        capRows[#capRows + 1] = { isHeader = true, title = group.title:upper() }
        for _, key in ipairs(group.keys) do
            local state, note = WTM.Caps:Get(key)
            capRows[#capRows + 1] = {
                key = key,
                label = WTM.Caps.LABELS[key] or key,
                state = state,
                note = note,
            }
        end
    end
    self.capList:SetData(capRows)
end
